sudo: required
language: node_js
notifications:
  email: false
node_js:
  - 6
  - 8
  - 10
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10
script: npm run travis
before_install:
  - npm i -g npm
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -q
  - sudo apt-get install -y proj-bin gdal-bin
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
